# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sdayani\Documents\GitHub\BAMline4CT\DevelopinSandbox\Ui_files\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftPannel = QtWidgets.QWidget(self.centralwidget)
        self.leftPannel.setObjectName("leftPannel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftPannel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5.addWidget(self.leftPannel)
        self.rightpannel = QtWidgets.QWidget(self.centralwidget)
        self.rightpannel.setObjectName("rightpannel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightpannel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rightUpper = QtWidgets.QWidget(self.rightpannel)
        self.rightUpper.setObjectName("rightUpper")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rightUpper)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addWidget(self.rightUpper)
        self.rightLower = QtWidgets.QWidget(self.rightpannel)
        self.rightLower.setObjectName("rightLower")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rightLower)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.rightLower)
        self.progressBar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.rightLower)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_5.addWidget(self.rightpannel)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Import_Folder_s = QtWidgets.QAction(MainWindow)
        self.action_Import_Folder_s.setObjectName("action_Import_Folder_s")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_Import_Folder_s)
        self.menu_File.addAction(self.action_Settings)
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.action_Exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BAMline 4D CT Reco "))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_Import_Folder_s.setText(_translate("MainWindow", "&Import Folder(s)"))
        self.action_Settings.setText(_translate("MainWindow", "&Settings"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
