# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sdayani\Documents\GitHub\BAMline4CT\DevelopinSandbox\Ui_files\QueeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QueeWidget(object):
    def setupUi(self, QueeWidget):
        QueeWidget.setObjectName("QueeWidget")
        QueeWidget.resize(426, 397)
        self.verticalLayout = QtWidgets.QVBoxLayout(QueeWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TreePlaceHolder = QtWidgets.QWidget(QueeWidget)
        self.TreePlaceHolder.setObjectName("TreePlaceHolder")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TreePlaceHolder)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.TreePlaceHolder)
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.verticalLayout.addWidget(self.TreePlaceHolder)
        self.widget = QtWidgets.QWidget(QueeWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_selected_setting = QtWidgets.QPushButton(self.widget)
        self.btn_selected_setting.setObjectName("btn_selected_setting")
        self.horizontalLayout_2.addWidget(self.btn_selected_setting)
        self.btn_copy = QtWidgets.QPushButton(self.widget)
        self.btn_copy.setObjectName("btn_copy")
        self.horizontalLayout_2.addWidget(self.btn_copy)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.ButtonPlaceHolder = QtWidgets.QWidget(QueeWidget)
        self.ButtonPlaceHolder.setObjectName("ButtonPlaceHolder")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ButtonPlaceHolder)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_import = QtWidgets.QPushButton(self.ButtonPlaceHolder)
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        self.btn_settings = QtWidgets.QPushButton(self.ButtonPlaceHolder)
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout.addWidget(self.btn_settings)
        self.btn_reco = QtWidgets.QPushButton(self.ButtonPlaceHolder)
        self.btn_reco.setObjectName("btn_reco")
        self.horizontalLayout.addWidget(self.btn_reco)
        self.verticalLayout.addWidget(self.ButtonPlaceHolder)

        self.retranslateUi(QueeWidget)
        QtCore.QMetaObject.connectSlotsByName(QueeWidget)

    def retranslateUi(self, QueeWidget):
        _translate = QtCore.QCoreApplication.translate
        QueeWidget.setWindowTitle(_translate("QueeWidget", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("QueeWidget", "Item"))
        self.treeWidget.headerItem().setText(1, _translate("QueeWidget", "Value"))
        self.btn_selected_setting.setText(_translate("QueeWidget", "Copy selected settings"))
        self.btn_copy.setText(_translate("QueeWidget", "Copy All Settings"))
        self.btn_import.setText(_translate("QueeWidget", "Import ..."))
        self.btn_settings.setText(_translate("QueeWidget", "Settings..."))
        self.btn_reco.setText(_translate("QueeWidget", "Reco all"))
