# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sdayani\Documents\GitHub\BAMline4CT\DevelopinSandbox\Ui_files\SettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(424, 584)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SettingsWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(SettingsWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Import = QtWidgets.QWidget()
        self.tab_Import.setObjectName("tab_Import")
        self.textEdit = QtWidgets.QTextEdit(self.tab_Import)
        self.textEdit.setGeometry(QtCore.QRect(380, 50, 321, 161))
        self.textEdit.setObjectName("textEdit")
        self.btn_import_load = QtWidgets.QPushButton(self.tab_Import)
        self.btn_import_load.setGeometry(QtCore.QRect(40, 300, 75, 23))
        self.btn_import_load.setObjectName("btn_import_load")
        self.groupBox = QtWidgets.QGroupBox(self.tab_Import)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 264, 114))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.radio_rotation_data_yes = QtWidgets.QRadioButton(self.groupBox)
        self.radio_rotation_data_yes.setObjectName("radio_rotation_data_yes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radio_rotation_data_yes)
        self.radio_rotation_data_yes_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_rotation_data_yes_2.setObjectName("radio_rotation_data_yes_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radio_rotation_data_yes_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.txt_rotation_data_path = QtWidgets.QLineEdit(self.groupBox)
        self.txt_rotation_data_path.setObjectName("txt_rotation_data_path")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.txt_rotation_data_path)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_Import)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 264, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.txt_projection_data_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_projection_data_path.setObjectName("txt_projection_data_path")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.txt_projection_data_path)
        self.tabWidget.addTab(self.tab_Import, "")
        self.tab_ImageJ = QtWidgets.QWidget()
        self.tab_ImageJ.setObjectName("tab_ImageJ")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_ImageJ)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_ImageJ)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txt_epics_channel_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_epics_channel_name.setObjectName("txt_epics_channel_name")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_epics_channel_name)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.btn_connect = QtWidgets.QPushButton(self.tab_ImageJ)
        self.btn_connect.setObjectName("btn_connect")
        self.verticalLayout_3.addWidget(self.btn_connect)
        self.tabWidget.addTab(self.tab_ImageJ, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(260, 140, 301, 231))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 450, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 30, 261, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_8)
        self.txt_volume_path = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_volume_path.setObjectName("txt_volume_path")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.txt_volume_path)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 190, 271, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_10)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_3)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_4)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBox_7)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBox_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(110, 410, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 80, 301, 231))
        self.textEdit_3.setObjectName("textEdit_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(SettingsWidget)
        self.widget_2.setObjectName("widget_2")
        self.btn_apply = QtWidgets.QPushButton(self.widget_2)
        self.btn_apply.setGeometry(QtCore.QRect(50, 0, 75, 23))
        self.btn_apply.setObjectName("btn_apply")
        self.btn_cancel = QtWidgets.QPushButton(self.widget_2)
        self.btn_cancel.setGeometry(QtCore.QRect(150, 0, 75, 23))
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_load_setting = QtWidgets.QPushButton(self.widget_2)
        self.btn_load_setting.setGeometry(QtCore.QRect(250, 0, 91, 21))
        self.btn_load_setting.setObjectName("btn_load_setting")
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(SettingsWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingsWidget.setWindowTitle(_translate("SettingsWidget", "Form"))
        self.label.setText(_translate("SettingsWidget", "Settings Menu"))
        self.textEdit.setHtml(_translate("SettingsWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">this section needs to be field with : </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if the hdf5 file contains speed W or not (*check box )</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if it does, then where is the path to the data ? </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">where are the projections stored ? (path in hdf5 file) </p></body></html>"))
        self.btn_import_load.setText(_translate("SettingsWidget", "load settings "))
        self.groupBox.setTitle(_translate("SettingsWidget", "Rotation speed "))
        self.label_3.setText(_translate("SettingsWidget", "does hdf5 file contain rotation speed data ? "))
        self.radio_rotation_data_yes.setText(_translate("SettingsWidget", "yes"))
        self.radio_rotation_data_yes_2.setText(_translate("SettingsWidget", "No"))
        self.label_4.setText(_translate("SettingsWidget", "please provide the path to the rotation speed data"))
        self.groupBox_2.setTitle(_translate("SettingsWidget", "Projection data"))
        self.label_6.setText(_translate("SettingsWidget", "please provide the path to the projection data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Import), _translate("SettingsWidget", "Import Settings"))
        self.groupBox_3.setTitle(_translate("SettingsWidget", "GroupBox"))
        self.label_5.setText(_translate("SettingsWidget", "EPICS channel Name :"))
        self.btn_connect.setText(_translate("SettingsWidget", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ImageJ), _translate("SettingsWidget", "ImageJ Pluggin"))
        self.textEdit_2.setHtml(_translate("SettingsWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">save setting : </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3D save : </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">where should we save volume, </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">where should we save metadata  ? (path to hdf5 file )</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4D data saving : </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">we need to think of a way for this . how to link datasets . or if we can create a special kind of data set </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_4.setText(_translate("SettingsWidget", "load Settings"))
        self.groupBox_4.setTitle(_translate("SettingsWidget", "Hdf 5 File Format"))
        self.label_8.setText(_translate("SettingsWidget", "Please provide the path to save Volume "))
        self.groupBox_5.setTitle(_translate("SettingsWidget", "meta data "))
        self.label_10.setText(_translate("SettingsWidget", "Please provide the desired metadata to write:"))
        self.label_2.setText(_translate("SettingsWidget", "TextLabel"))
        self.checkBox.setText(_translate("SettingsWidget", "CheckBox"))
        self.label_7.setText(_translate("SettingsWidget", "TextLabel"))
        self.checkBox_2.setText(_translate("SettingsWidget", "CheckBox"))
        self.label_11.setText(_translate("SettingsWidget", "TextLabel"))
        self.checkBox_3.setText(_translate("SettingsWidget", "CheckBox"))
        self.label_12.setText(_translate("SettingsWidget", "TextLabel"))
        self.checkBox_4.setText(_translate("SettingsWidget", "CheckBox"))
        self.label_15.setText(_translate("SettingsWidget", "TextLabel"))
        self.checkBox_7.setText(_translate("SettingsWidget", "CheckBox"))
        self.label_14.setText(_translate("SettingsWidget", "TextLabel"))
        self.checkBox_6.setText(_translate("SettingsWidget", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsWidget", "Save Settings"))
        self.pushButton_6.setText(_translate("SettingsWidget", "load Settings"))
        self.textEdit_3.setHtml(_translate("SettingsWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">reconstruction settings : </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">n cores </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">GPU  ? </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">etc. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingsWidget", "Reco Settings"))
        self.btn_apply.setText(_translate("SettingsWidget", "Apply"))
        self.btn_cancel.setText(_translate("SettingsWidget", "Cancel"))
        self.btn_load_setting.setText(_translate("SettingsWidget", "Load Settings"))
